[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true

[watch]
watch = []
ignore = []

[serve]
address = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = true

# [[proxy]]
# # This proxy example has a backend and a rewrite field. Requests received on `rewrite` will be
# # proxied to the backend after rewriting the `rewrite` prefix to the `backend`'s URI prefix.
# # E.G., `/api/v1/resource/x/y/z` -> `/resource/x/y/z`
# rewrite = "/api/v1/"
# backend = "http://localhost:9000/"

# [[proxy]]
# # This proxy specifies only the backend, which is the only required field. In this example,
# # request URIs are not modified when proxied.
# backend = "http://localhost:9000/api/v2/"

# [[proxy]]
# # This proxy example has an insecure field. In this example,
# # connections to https://localhost:9000/api/v3/ will not have certificate validation performed.
# # This is useful for development with a server using self-signed certificates.
# backend = "https://localhost:9000/api/v3/"
# insecure = true
